[package]
name = "rust_p2p_dex"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.53", features = ["tcp", "tokio", "mdns", "gossipsub"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
